repository: ocp-tests
variants:
 - name: okd
   attributes:
    - _attributes/okd-attributes.adoc
   build: true
   files:
     included:
       - architecture/**/*.adoc
       - welcome/**/*.adoc
       - modules/**/*.adoc
       - whats_new/**/*.adoc
       - installing/**/*.adoc
 - name: openshift-container-platform
   attributes:
    - _attributes/ocp-attributes.adoc
   build: true
   files:
     included:
       - architecture/**/*.adoc
       - welcome/**/*.adoc
       - modules/**/*.adoc
       - release_notes/**/*.adoc
       - installing/**/*.adoc
 - name: openshift-dedicated
   attributes:
    - _attributes/osd-attributes.adoc
   build: true
   files:
     included:
       - architecture/**/*.adoc
       - welcome/**/*.adoc
       - modules/**/*.adoc
       - getting_started/**/*.adoc
       - cloud_infrastructure_access/**/*.adoc
       - administering_a_cluster/**/*.adoc
