repository: ocp-tests
variants:
 - name: okd
   attributes:
     - _artifacts/okd-attributes.adoc
   nav: _artifacts/toc.yml
   build: true
   files:
     included:
       - architecture/**/*.adoc
       - architecture/*.adoc
       - welcome/**/*.adoc
       - welcome/*.adoc
       - modules/**/*.adoc
       - modules/*.adoc
       - whats_new/**/*.adoc
       - whats_new/*.adoc
       - installing/**/*.adoc
       - installing/*.adoc
     excluded:
       - _unused_topics
       - _package
       - _stylesheets
       - scripts
       - getting_started
       - cloud_infrastructure_access
       - administering_a_cluster
 - name: openshift-container-platform
   attributes:
     - _attributes/ocp-attributes.adoc
   nav: _artifacts/toc.yml
   build: false
   files:
     included:
       - architecture/**/*.adoc
       - architecture/*.adoc
       - welcome/**/*.adoc
       - welcome/*.adoc
       - modules/**/*.adoc
       - modules/*.adoc
       - whats_new/**/*.adoc
       - whats_new/*.adoc
       - installing/**/*.adoc
       - installing/*.adoc
     excluded:
       - _unused_topics
       - _package
       - _stylesheets
       - scripts
       - whats_new
       - getting_started
       - cloud_infrastructure_access
       - administering_a_cluster
 - name: openshift-dedicated
   attributes:
     - _artifacts/osd-attributes.adoc
   nav: _artifacts/toc.yml
   build: false
   files:
     included:
       - architecture/**/*.adoc
       - architecture/*.adoc
       - welcome/**/*.adoc
       - welcome/*.adoc
       - modules/**/*.adoc
       - modules/*.adoc
       - whats_new/**/*.adoc
       - whats_new/*.adoc
       - installing/**/*.adoc
       - installing/*.adoc
       - getting_started/**/*.adoc
       - getting_started/*.adoc
       - cloud_infrastructure_access/**/*.adoc
       - cloud_infrastructure_access/*.adoc
       - administering_a_cluster/**/*.adoc
       - administering_a_cluster/*.adoc
     excluded:
       - _unused_topics
       - _package
       - _stylesheets
       - scripts
       - installing
       - whats_new
