repository: ocp-tests
variants:
 - name: okd
   attributes:
     - _artifacts/okd-attributes.adoc
   nav: _artifacts/toc.yml
   build: true
   files:
     included:
       - architecture/**/*.adoc
       - welcome/**/*.adoc
       - modules/**/*.adoc
       - whats_new/**/*.adoc
       - installing/**/*.adoc
     excluded:
       - _unused_topics
       - _package
       - _stylesheets
       - scripts
       - getting_started
       - cloud_infrastructure_access
       - administering_a_cluster
