repository: ocp-tests
variants:
 - name: ocp
   attributes:
     - _artifacts/ocp-attributes.adoc
   nav: _artifacts/toc.yml
   build: true
   files:
     included:
       - architecture/**/*.adoc
       - architecture/*.adoc
       - welcome/**/*.adoc
       - welcome/*.adoc
       - modules/**/*.adoc
       - modules/*.adoc
       - whats_new/**/*.adoc
       - whats_new/*.adoc
       - installing/**/*.adoc
       - installing/*.adoc
