repository: ocp-tests
variants:
 - name: okd
   attributes:
    - _artifacts/okd-attributes.adoc
   build: true
   files:
     included:
       - architecture/**/*.adoc
       - welcome/**/*.adoc
       - modules/**/*.adoc
       - whats_new/**/*.adoc
       - installing/**/*.adoc
 - name: openshift-container-platform
   attributes:
    - _artifacts/ocp-attributes.adoc
   build: true
   files:
     included:
       - architecture/**/*.adoc
       - welcome/**/*.adoc
       - modules/**/*.adoc
       - release_notes/**/*.adoc
       - installing/**/*.adoc
- name: openshift-dedicated
  attributes:
   - _artifacts/osd-attributes.adoc
  build: true
  files:
    included:
      - architecture/**/*.adoc
      - welcome/**/*.adoc
      - modules/**/*.adoc
      dedicated
      - getting_started/**/*.adoc
      - cloud_infrastructure_access/**/*.adoc
      - administering_a_cluster/**/*.adoc
